# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodTruck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodTruck

  pod ‘Firebase/Core’
  pod ‘Firebase/Auth’
  pod ‘Firebase/Database’
  pod ‘Firebase/Storage’
  pod ‘Alamofire’
  pod ‘AlamofireImage’
  pod 'GoogleSignIn'
  pod ‘FirebaseUI/Storage'

end
